### PR TITLE
Spanish translation for Readme

### PR DESCRIPTION
**Pull request by carlmylo**
Includes Spanish Clone Hero screenshots.
Also updated "Controller Type" to "Controller Emulation Mode" in English readme to accurately reflect current terminology.
Will translate the misc documentation (WinUSB, Debugging, GuitarSniffer) at a later date.

I will get @Lynxeption to double check grammar in the afternoon.

### CODE REVIEW

**Comment by TheNathannator** [comment]
Awesome stuff! Will merge once Lynxeption does that proofreading.

**Comment by Lynxeption** [comment]
hey there! thanks for getting me involved with the project haha

i predict that the proof reading will probably be done either tonight or tomorrow morning since i'm sending the individual corrections of strings to CarlMylo via discord DMs, but rest assured progress is going fine :)

**Comment by TheNathannator** [comment]
No worries, take your time!

**Comment by TheNathannator** [comment]
Everything look all good now?

**Comment by carlmylo** [comment]
Should be good.

**Comment by TheNathannator** [comment]
Awesome, merging now!

**Pull request merged**
